# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Pere Urbon-Bayes / Software Architect
email: pere.urbon@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 Software Architect and data enginner with a background in data processing infrastructure and information retrieval
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://purbon.github.io/" # the base hostname & protocol for your site, e.g. http://example.com
baseurl:             ''
paginate: 5
paginate_path: "/posts/page:num/"
permalink:           pretty
twitter_username: purbon
github_username:  purbon

# Build settings
markdown: kramdown
theme: jekyll-theme-lanyon
plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-gist
  - jekyll-paginate
  - jekyll-seo-tag

menus:
  header:
    - title: Home
      identifier: home
      url: /
    - title: Cv
      identifier: cv
      url: /cv
    - title: Blog
      identifier: posts
      url: /posts
    - title: Services
      identifier: services
      url: /services
    - title: About
      identifier: about
      url: /about

sass:
  sass_dir: _sass
  style: :compressed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
